### ISSUE TITLE
Connecting ways

### ISSUE THREAD

**Issue by philam** [microsoft/Open-Maps#40]
Thanks for your work so far in Australia - it's been very helpful!

Just wanted to give some feedback about connecting ways. I've come across a few edits around Victoria where ways have been connected to create junctions while none actually exist on the ground. This then creates issues with incorrect routing and misleading spatial information.

**Comment by BrackoNe** [comment]
Hi philam,

Thank you for the feedback. Can you please point to exact place where issue has been produced (coordinates or URL)?
I would like personally to step into it.

Thank you,
Nemanja
OSM Lead

**Comment by philam** [comment]
Thanks, I don't want to dob anyone in and get them into trouble as the work you're doing is valuable, but here is the most recent example (I have since fixed this): https://www.openstreetmap.org/changeset/67420594

**Comment by BrackoNe** [comment]
Thanks for pointing this out.

I have checked this one. I can see what the potential problem might be. Our editors were fixing Osmose issues in the best possible manner. It might be some (very rare) cases that they've made an mistake in decision whether it should be connected, or it needs to have "noexit" tag. The mistake is possibly done only on footways or similar "highways", because our editors have contacted many users if there is some suspicious situation with higher road priority.

For your information, this was one of the last tasks we have made in Australia, and we have tried to fix **~6,500** (logical) issues that have been produced by other users in last 6 months. In iteration before this, we have fixed **25,000** issues as well.

Once again, please accept our apology if you find any issue like this, but I'm 100% sure that there are only few of them.

Thanks a lot,
Nemanja

**Comment by TimuSumisu** [comment]
Closing this issue. Feedback has been folded into our editorial and QC process.

Thanks as always for the feedback and open new issues should anything stand out!
